version: '3.9'

networks:
  ai_network:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        USE_CN_SOURCE: ${USE_CN_SOURCE:-true}  # 使用环境变量，如果没有设置则默认使用 true
    container_name: backend
    ports:
      - "10085:10085"
    networks:
      - ai_network
    restart: unless-stopped

  frontend:
    build:
      context: ./web
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "10085:80"
    networks:
      - ai_network
    restart: unless-stopped
